# Generated by Django 5.2.7 on 2025-10-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('review', '0002_remove_review_user'),
        ('venue', '0002_alter_venue_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
