# Generated by Django 5.2.7 on 2025-10-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_username_alter_profile_user'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='user.profile'),
        ),
    ]
