# # Generated by Django 5.2.7 on 2025-10-17 19:19

# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('user', '0001_initial'),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='profile',
#             name='username',
#         ),
#         migrations.AlterField(
#             model_name='profile',
#             name='user',
#             field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#         ),
#     ]
